### PR TITLE
Changing Apple Maps URL and refactoring code

### PR DESCRIPTION
**Pull request by hpbl**
Hey, your code was really helpful for me, so I decided to add some comments and, try to improve the readability of your example.

I also updated the Apple Maps URL to use https, since the old one on the repo didn't seem to work on my project.

I hope you don't mind 😁

### CODE REVIEW

**Comment by zirinisp** [comment]
it is good to hear that my repository was helpful.

updates and changes are always welcome. give me some time to check out the pull request and merge it.

**Review by zirinisp — APPROVED** [review]
It was something that I always wanted to do and never found the time.

Thank you for improving the code

**Comment by hpbl** [comment]
I am really glad you've approved.

keep up the good work!

**Comment by zirinisp** [comment]
@hpbl Just checking if you have received my email on 30/10

**Comment by hpbl** [comment]
Im sorry, I did receive it, I just didn't have the time to answer it
properly. I shall be doing that today, is that okay?

**Comment by zirinisp** [comment]
That is fine. I was just worried that it got to your spam.

**Pull request merged**
